# Generated by Django 2.2 on 2020-02-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group_App', '0002_group_groupmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupManager',
        ),
    ]
